Repository iver-wharf/wharf-provider-azuredevops, pull requests merged in 2021-09, with the labels that each got.

#31 Import repos, and not projects
  CHANGELOG.md
  README.md
  azuredevops.go
  azuredevops_test.go
  go.mod
  go.sum
  internal/azureapi/client.go
  internal/azureapi/models.go
  internal/importer/importer.go
  pkg/requests/errors.go
  pkg/requests/requests.go
  util.go
  util_test.go
Labels: bug, enhancement

#33 Changed InsecureSkipVerify to be opt-in
  CHANGELOG.md
  azuredevops.go
  config.go
  internal/importer/importer.go
  main.go
Labels: enhancement

#32 Release v2.0.0
  CHANGELOG.md
Labels: release

#35 Updated Docker base images
  CHANGELOG.md
  Dockerfile
Labels: bug

#36 Release v2.0.1
  CHANGELOG.md
Labels: release

#37 Added "--pull" to docker build
  Makefile
Labels: enhancement

#28 Changed to use wharf-core/pkg/cacertutil instead of internal/httputils
  CHANGELOG.md
  go.mod
  go.sum
  internal/httputils/httpclient.go
  main.go
Labels: enhancement
